# Generated by Django 5.0.6 on 2024-06-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_fr', models.CharField(max_length=200)),
                ('content_en', models.TextField()),
                ('content_fr', models.TextField()),
                ('publication_date', models.DateTimeField()),
            ],
        ),
    ]
